"""Make session user_id nullable

Revision ID: 685eb2329777
Revises: 001
Create Date: 2026-05-26 01:28:21.316137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '685eb2329777'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analytics_event_type'), 'analytics', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_session_id'), 'analytics', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_user_id'), 'analytics', ['user_id'], unique=False)
    op.add_column('memory_metadata', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('memory_metadata', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('memory_metadata', sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('memory_metadata', 'memory_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('memory_metadata', 'qdrant_point_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_memory_metadata_memory_type'), 'memory_metadata', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_metadata_user_id'), 'memory_metadata', ['user_id'], unique=False)
    op.drop_constraint(op.f('memory_metadata_user_id_fkey'), 'memory_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'memory_metadata', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('memory_metadata', 'content_summary')
    op.drop_column('memory_metadata', 'access_count')
    op.drop_column('memory_metadata', 'importance_score')
    op.drop_column('memory_metadata', 'last_accessed')
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('messages_session_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'metadata_json')
    op.alter_column('sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.alter_column('sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('messages', sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('messages_session_id_fkey'), 'messages', 'sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_column('messages', 'updated_at')
    op.add_column('memory_metadata', sa.Column('last_accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('memory_metadata', sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('memory_metadata', sa.Column('access_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('memory_metadata', sa.Column('content_summary', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'memory_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('memory_metadata_user_id_fkey'), 'memory_metadata', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_memory_metadata_user_id'), table_name='memory_metadata')
    op.drop_index(op.f('ix_memory_metadata_memory_type'), table_name='memory_metadata')
    op.alter_column('memory_metadata', 'qdrant_point_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('memory_metadata', 'memory_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('memory_metadata', 'metadata_json')
    op.drop_column('memory_metadata', 'relevance_score')
    op.drop_column('memory_metadata', 'content')
    op.drop_index(op.f('ix_analytics_user_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_session_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_event_type'), table_name='analytics')
    # ### end Alembic commands ###
