"""Add support sessions and messages

Revision ID: c5dcb64488b2
Revises: 685eb2329777
Create Date: 2026-05-29 22:08:12.156713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5dcb64488b2'
down_revision = '685eb2329777'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_sessions',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('discord_thread_id', sa.String(), nullable=True),
    sa.Column('websocket_room_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_activity', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_sessions_discord_thread_id'), 'support_sessions', ['discord_thread_id'], unique=True)
    op.create_index(op.f('ix_support_sessions_user_id'), 'support_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_support_sessions_websocket_room_id'), 'support_sessions', ['websocket_room_id'], unique=True)
    op.create_table('support_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['support_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_session_id'), 'support_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_messages_session_id'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_support_sessions_websocket_room_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_user_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_discord_thread_id'), table_name='support_sessions')
    op.drop_table('support_sessions')
    # ### end Alembic commands ###
